### ISSUE TITLE
MacBook CUDA error

### ISSUE THREAD

**Issue by vipic** [PlayVoice/so-vits-svc-5.0#17]
M1 MacBook 报错见下。是不是意味着只有 NVIDIA 显卡才行

    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by MaxMax2016** [comment]
需要修改代码吧 https://github.com/Stability-AI/StableLM/issues/31

**Comment by vipic** [comment]
> 



> 需要修改代码吧 [Stability-AI/StableLM#31](https://github.com/Stability-AI/StableLM/issues/31)

好的，我去试试看

**Comment by vipic** [comment]
这个步骤暂时解决了，但是我还是不弄了。

/prepare/preprocess_speaker.py 文件，77 行有个 if use_cuda 的判断，将这里调整参数或者注释掉就能短暂的进行下去了。

后续启动训练的时候还会继续报错，

svc_trainer.py 文件 33 行判断直接打印 "No GPU find!"

后续这个文件又调用 vits_extend/tran.py，里面 还有和 cuda 相关代码，找到 pytorch 里面提到 torch.cuda() 替换为 torch.cpu() 就能切换使用 cpu 来训练。但是这里还有一些参数不知道什么含义，我不准备继续了...
